"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Container } from "@/components/ui/container";

const steps = ["Personal information", "Company information", "Products of interest", "Sourcing countries", "Complete profile"];
export default function BuyerOnboardingPage() { const [step, setStep] = useState(0); const router = useRouter(); const done = step === steps.length - 1; return <Wizard title="Set up your buyer profile" steps={steps} step={step}><p className="text-sm text-slate-600">{steps[step]}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label={step === 0 ? "Full name" : step === 1 ? "Company name" : step === 2 ? "Products or categories" : step === 3 ? "Preferred sourcing countries" : "Profile summary"} /><Field label={step === 0 ? "Job title" : step === 1 ? "Industry" : "Additional notes"} required={false} /></div><div className="mt-8 flex justify-between gap-3"><button disabled={step === 0} onClick={() => setStep(step - 1)} className="rounded-full border border-slate-200 px-5 py-3 text-sm font-semibold text-slate-700 disabled:opacity-40">Back</button><div className="flex gap-3"><button onClick={() => done ? router.push("/marketplace") : setStep(step + 1)} className="rounded-full bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">{done ? "Start Buying" : "Continue"}</button>{step > 1 && !done && <button onClick={() => setStep(step + 1)} className="px-3 text-sm font-semibold text-slate-500">Skip</button>}</div></div></Wizard>; }
function Wizard({ title, steps, step, children }: { title: string; steps: string[]; step: number; children: React.ReactNode }) { return <main className="py-12"><Container><div className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-indigo-600">Buyer onboarding</p><h1 className="mt-3 text-3xl font-bold text-slate-900">{title}</h1><div className="mt-8 flex gap-1">{steps.map((label, index) => <div key={label} className={`h-2 flex-1 rounded-full ${index <= step ? "bg-indigo-600" : "bg-slate-100"}`} aria-label={label} />)}</div><p className="mt-3 text-xs font-semibold text-slate-500">Step {step + 1} of {steps.length}</p><div className="mt-8">{children}</div></div></Container></main>; }
function Field({ label, required = true }: { label: string; required?: boolean }) { return <label className="text-sm font-medium text-slate-700">{label}<input required={required} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 outline-none focus:border-indigo-500" /></label>; }
