"use client";

import Link from "next/link";
import { products } from "@/lib/data/marketplace";
import { supplierStats, supplierInquiries, orders, verificationItems } from "@/lib/data/platform";
import { Card } from "@/components/ui/card";
import { PlatformShell, StatCard, Status, QuickLink } from "@/components/platform/PlatformUI";

export function SupplierWorkspace({ view = "dashboard" }: { view?: string }) {
  if (view === "add") return <AddProduct />;
  if (view === "verification") return <Verification />;
  const titles: Record<string, string> = { dashboard: "Good morning, SolarTech Africa", profile: "Company profile", products: "Product management", orders: "Orders", inquiries: "Buyer inquiries", messages: "Messages", settings: "Supplier settings" };
  if (view !== "dashboard") return <PlatformShell eyebrow="Supplier workspace" title={titles[view] ?? "Supplier workspace"} description="Manage your supplier operations from one connected workspace."><Card className="mt-8"><h2 className="text-lg font-semibold">{titles[view]}</h2>{view === "products" ? <div className="mt-4 space-y-3">{products.map((p) => <Link key={p.id} href={`/marketplace/product/${p.slug}`} className="flex justify-between rounded-lg bg-slate-50 p-4"><span>{p.name}<small className="mt-1 block text-slate-500">SKU {p.sku}</small></span><Status>Published</Status></Link>)}</div> : view === "inquiries" ? <div className="mt-4 space-y-3">{supplierInquiries.map((i) => <div key={i.title} className="flex justify-between rounded-lg bg-slate-50 p-4"><span>{i.title}<small className="mt-1 block text-slate-500">{i.buyer}</small></span><Status>{i.status}</Status></div>)}</div> : view === "orders" ? <div className="mt-4 space-y-3">{orders.map((o) => <div key={o.id} className="flex justify-between rounded-lg bg-slate-50 p-4"><span>{o.title}</span><Status>{o.status}</Status></div>)}</div> : <p className="mt-3 text-slate-600">This workspace is ready for connected supplier data.</p>}</Card></PlatformShell>;
  return <PlatformShell eyebrow="Supplier workspace" title={titles.dashboard} description="Manage your catalog, inquiries and orders from one operational workspace." action={<Link href="/supplier/products/add" className="rounded-full bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Add product</Link>}><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{supplierStats.map((s) => <StatCard key={s.label} {...s} />)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-lg font-semibold">Recent inquiries</h2><div className="mt-4 space-y-3">{supplierInquiries.map((i) => <Link href="/supplier/inquiries" key={i.title} className="flex justify-between rounded-lg bg-slate-50 p-4"><span>{i.title}<small className="mt-1 block text-slate-500">{i.buyer}</small></span><Status>{i.status}</Status></Link>)}</div></Card><Card><h2 className="text-lg font-semibold">Verification status</h2><p className="mt-3 text-slate-600">Your company profile is 67% complete.</p><Link href="/supplier/verification" className="mt-5 inline-flex text-sm font-semibold text-indigo-600">Review verification</Link></Card></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><QuickLink href="/supplier/products" title="Products" description="Manage your catalog" /><QuickLink href="/supplier/inquiries" title="Inquiries" description="Respond to buyers" /><QuickLink href="/supplier/orders" title="Orders" description="Track fulfillment" /><QuickLink href="/supplier/messages" title="Messages" description="Talk with buyers" /></div></PlatformShell>;
}

function AddProduct() { return <PlatformShell eyebrow="Supplier workspace" title="Add a product" description="Prepare a buyer-facing listing. Actions are mock-only until the backend is connected."><Card className="mt-8"><form onSubmit={(e) => e.preventDefault()} className="grid gap-4 sm:grid-cols-2">{["Product name", "Category", "Subcategory", "MOQ", "Price", "Price range", "Currency", "Stock / availability", "Lead time", "Product keywords / tags"].map((label) => <label key={label} className="text-sm text-slate-600">{label}<input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2" /></label>)}<label className="text-sm text-slate-600 sm:col-span-2">Product description<textarea className="mt-1 min-h-28 w-full rounded-lg border border-slate-200 px-3 py-2" /></label><label className="rounded-xl border-2 border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 sm:col-span-2">Drag and drop product images or browse<input type="file" multiple className="mt-3 block w-full text-xs" /></label><label className="text-sm text-slate-600 sm:col-span-2">Specifications, certifications and shipping information<textarea className="mt-1 min-h-24 w-full rounded-lg border border-slate-200 px-3 py-2" /></label><div className="flex gap-3 sm:col-span-2"><button type="button" className="rounded-full border border-slate-300 px-4 py-2 text-sm font-semibold">Save draft</button><button className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Publish product</button></div></form></Card></PlatformShell>; }
function Verification() { return <PlatformShell eyebrow="Trust and safety" title="Supplier verification" description="Build buyer confidence with a complete, reviewable company profile."><Card className="mt-8"><div className="flex justify-between"><h2 className="text-lg font-semibold">Verification progress</h2><strong className="text-emerald-700">67%</strong></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 w-2/3 rounded-full bg-emerald-500" /></div><div className="mt-5 divide-y divide-slate-200">{verificationItems.map((i) => <div key={i.label} className="flex justify-between py-4"><span>{i.label}</span><Status>{i.status}</Status></div>)}</div></Card></PlatformShell>; }
