"use client";

import Link from "next/link";
import { useState } from "react";
import { Container } from "@/components/ui/container";

export function AuthForm({ mode = "login" }: { mode?: "login" | "register" }) {
  const [role, setRole] = useState<"buyer" | "supplier">("buyer");
  const [showPassword, setShowPassword] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [remember, setRemember] = useState(true);
  const isRegister = mode === "register";
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); localStorage.setItem("nsomex_mock_user", JSON.stringify({ role, remembered: remember })); setSubmitted(true); }
  if (submitted) return <main className="py-16"><Container><div className="mx-auto max-w-lg rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><div className="text-3xl text-emerald-600">✓</div><h1 className="mt-4 text-2xl font-bold">{isRegister ? "Your mock account is ready" : "Welcome back"}</h1><p className="mt-2 text-slate-600">This frontend demo saved your session locally. No real authentication service has been connected.</p><Link href={role === "supplier" ? "/supplier/dashboard" : "/account"} className="mt-6 inline-flex rounded-full bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Continue to dashboard</Link></div></Container></main>;
  return <main className="py-12"><Container><div className="mx-auto max-w-xl"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-indigo-600">NSOMEX account</p><h1 className="mt-3 text-3xl font-bold text-slate-900">{isRegister ? "Create your marketplace account" : "Sign in to NSOMEX"}</h1><p className="mt-2 text-slate-600">{isRegister ? "Join a trusted procurement network for Africa and beyond." : "Continue to your procurement workspace."}</p></div><form onSubmit={submit} className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-1"><button type="button" onClick={() => setRole("buyer")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${role === "buyer" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>Buyer</button><button type="button" onClick={() => setRole("supplier")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${role === "supplier" ? "bg-white text-indigo-700 shadow-sm" : "text-slate-500"}`}>Supplier</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{isRegister && (role === "buyer" ? <Field label="Full name" /> : <><Field label="Contact person" /><Field label="Company name" /></>)}<Field label={role === "supplier" ? "Business email" : "Email"} type="email" /><Field label="Phone" /><Field label="Country" /></div><label className="mt-4 block text-sm text-slate-600">Password<div className="mt-1 flex rounded-lg border border-slate-200"><input required type={showPassword ? "text" : "password"} className="min-w-0 flex-1 rounded-lg px-3 py-2 outline-none" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="px-3 text-xs font-semibold text-indigo-600">{showPassword ? "Hide" : "Show"}</button></div></label><div className="mt-4 flex items-center justify-between text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /> Remember me</label><Link href="/login" className="font-medium text-indigo-600">Forgot password?</Link></div><button type="submit" className="mt-6 w-full rounded-full bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700">{isRegister ? "Create account" : "Sign in"}</button><p className="mt-5 text-center text-xs text-slate-500">By continuing, you agree to the NSOMEX terms and conditions.</p></form><p className="mt-5 text-center text-sm text-slate-600">{isRegister ? "Already have an account?" : "New to NSOMEX?"} <Link href={isRegister ? "/login" : "/register"} className="font-semibold text-indigo-600">{isRegister ? "Sign in" : "Register"}</Link></p></div></Container></main>;
}
function Field({ label, type = "text" }: { label: string; type?: string }) { return <label className="text-sm text-slate-600">{label}<input required type={type} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 outline-none focus:border-indigo-500" /></label>; }
