"use client";

import Link from "next/link";
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { PlatformShell, StatCard, Status } from "@/components/platform/PlatformUI";
import { procurementOrders, procurementQuotations, procurementInquiries, shipments } from "@/lib/data/procurement";

const orderStages = ["Order Placed", "Confirmed", "Production", "Ready for Shipment", "Shipped", "In Transit", "Delivered", "Completed"];

export function OrderCard({ order }: { order: any }) {
  return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/orders/${order.id}`} className="font-semibold text-slate-900 hover:text-indigo-700">{order.product}</Link><p className="mt-1 text-sm text-slate-500">{order.id} · {order.supplier}</p></div><Status>{order.status}</Status></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><span className="block text-slate-500">Quantity</span><strong>{order.quantity}</strong></div><div><span className="block text-slate-500">Total</span><strong>{order.total}</strong></div><div><span className="block text-slate-500">Payment</span><strong>{order.paymentStatus}</strong></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href={`/orders/${order.id}`} className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">View order</Link>{order.paymentStatus.includes("Pending") && <Link href={`/checkout/${order.id}`} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Pay securely</Link>}<Link href={`/tracking/${order.id}`} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Track shipment</Link></div></Card>;
}

export function OrderTimeline({ status }: { status: string }) {
  const current = Math.max(0, orderStages.findIndex((stage) => status.toLowerCase().includes(stage.toLowerCase().replace("order ", "")) || stage === status));
  return <div className="space-y-4">{orderStages.map((stage, index) => <div key={stage} className="flex gap-3"><div className={`mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index <= current ? "bg-indigo-600 text-white" : "bg-slate-100 text-slate-400"}`}>{index <= current ? "✓" : index + 1}</div><div><p className={`font-medium ${index === current ? "text-indigo-700" : "text-slate-800"}`}>{stage}</p>{index === current && <p className="text-sm text-slate-500">Current order stage</p>}</div></div>)}</div>;
}

export function ShipmentTimeline({ shipment }: { shipment: any }) {
  return <div className="space-y-4">{shipment.tracking.map((stage: string, index: number) => <div key={stage} className="flex gap-3"><div className={`mt-1 h-3 w-3 shrink-0 rounded-full ${index <= shipment.currentStep ? "bg-indigo-600" : "bg-slate-200"}`} /><div><p className={`text-sm font-medium ${index === shipment.currentStep ? "text-indigo-700" : "text-slate-800"}`}>{stage}</p>{index === shipment.currentStep && <p className="text-xs text-slate-500">Current location update</p>}</div></div>)}</div>;
}

export function ProductSummary({ order }: { order: any }) {
  return <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">Product summary</p><h2 className="mt-2 text-lg font-semibold text-slate-900">{order.product}</h2><p className="mt-1 text-sm text-slate-500">Supplied by {order.supplier}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Quantity</dt><dd className="font-semibold">{order.quantity}</dd></div><div><dt className="text-slate-500">Unit price</dt><dd className="font-semibold">{order.unitPrice}</dd></div><div><dt className="text-slate-500">Destination</dt><dd className="font-semibold">{order.destination}</dd></div></dl></Card>;
}

export function PaymentSummary({ order }: { order: any }) {
  return <Card className="p-5"><h2 className="font-semibold text-slate-900">Payment summary</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Products</dt><dd>{order.subtotal}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Shipping</dt><dd>{order.shipping}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Platform service fee</dt><dd>{order.serviceFee}</dd></div><div className="flex justify-between border-t border-slate-200 pt-3 text-base font-bold"><dt>Total</dt><dd>{order.total}</dd></div></dl></Card>;
}

export function QuotationCard({ quotation }: { quotation: any }) {
  return <Card className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{quotation.supplier}</h3><p className="mt-1 text-sm text-slate-500">{quotation.product} · {quotation.quantity}</p></div><Status>{quotation.status}</Status></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><span className="block text-slate-500">Supplier price</span><strong>{quotation.supplierPrice}</strong></div><div><span className="block text-slate-500">MOQ / lead time</span><strong>{quotation.moq} · {quotation.leadTime}</strong></div><div><span className="block text-slate-500">Terms</span><strong>{quotation.shippingTerms}</strong></div></div><p className="mt-4 text-sm text-slate-600">{quotation.message}</p><div className="mt-4 flex flex-wrap gap-3"><Link href={`/order/create/${quotation.rfqId}`} className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Create order</Link><Link href="/messages" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Continue negotiation</Link></div></Card>;
}

export function ProcurementWorkspace() {
  const stats = [{ label: "Open RFQs", value: "2", detail: "1 needs review" }, { label: "Supplier responses", value: String(procurementQuotations.length), detail: "Across active RFQs" }, { label: "Pending orders", value: "1", detail: "Payment required" }, { label: "Orders in production", value: "1", detail: "On schedule" }, { label: "Shipments in transit", value: "1", detail: "Tracking active" }, { label: "Completed orders", value: "1", detail: "Ready to review" }];
  return <PlatformShell eyebrow="Buyer procurement center" title="Procurement workspace" description="Move every sourcing request from supplier conversation to delivered order." action={<Link href="/rfq/create" className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Post an RFQ</Link>}><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stats.map((stat) => <StatCard key={stat.label} {...stat} />)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold text-slate-900">Active RFQs & inquiries</h2><Link href="/inquiries" className="text-sm font-semibold text-indigo-600">View all</Link></div><div className="mt-4 space-y-3">{procurementInquiries.slice(0, 2).map((item) => <Link key={item.id} href={`/inquiries#${item.id}`} className="block rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><span className="font-medium">{item.product}</span><Status>{item.status}</Status></div><p className="mt-1 text-sm text-slate-500">{item.supplier} · {item.lastMessage}</p></Link>)}</div></Card><Card className="p-5"><div className="flex justify-between"><h2 className="font-semibold text-slate-900">Supplier quotations</h2><Link href="/rfq/my-requests" className="text-sm font-semibold text-indigo-600">RFQ center</Link></div><div className="mt-4 space-y-3">{procurementQuotations.map((quote) => <Link key={quote.id} href={`/rfq/${quote.rfqId}`} className="block rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><span className="font-medium">{quote.supplier}</span><strong>{quote.supplierPrice}</strong></div><p className="mt-1 text-sm text-slate-500">{quote.product} · {quote.leadTime}</p></Link>)}</div></Card></div><div className="mt-8"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold text-slate-900">Active orders</h2><Link href="/orders" className="text-sm font-semibold text-indigo-600">Manage orders</Link></div><div className="grid gap-4 lg:grid-cols-2">{procurementOrders.slice(0, 2).map((order) => <OrderCard key={order.id} order={order} />)}</div></div><div className="mt-8"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold text-slate-900">Shipments</h2><Link href="/logistics" className="text-sm font-semibold text-indigo-600">Open logistics</Link></div><div className="grid gap-4 sm:grid-cols-2">{shipments.slice(0, 2).map((shipment) => <Card key={shipment.id} className="p-5"><div className="flex justify-between gap-3"><span className="font-semibold">{shipment.shipmentNumber}</span><Status>{shipment.status}</Status></div><p className="mt-2 text-sm text-slate-500">{shipment.supplier} · {shipment.destination}</p><Link href={`/tracking/${shipment.id}`} className="mt-4 inline-flex text-sm font-semibold text-indigo-600">Track shipment</Link></Card>)}</div></div></PlatformShell>;
}

export function InquiryWorkspace() {
  return <PlatformShell eyebrow="Buyer procurement" title="Inquiries & negotiations" description="Keep supplier conversations, pricing and next steps together."><div className="mt-8 space-y-4">{procurementInquiries.map((item) => <Card id={item.id} key={item.id} className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-slate-900">{item.product}</h2><p className="mt-1 text-sm text-slate-500">{item.supplier} · {item.date}</p></div><Status>{item.status}</Status></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><div><span className="block text-slate-500">Quantity</span><strong>{item.quantity}</strong></div><div><span className="block text-slate-500">Target price</span><strong>{item.targetPrice}</strong></div><div><span className="block text-slate-500">Quoted price</span><strong>{item.quotedPrice}</strong></div><div><span className="block text-slate-500">Last message</span><strong>{item.lastMessage}</strong></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href="/messages" className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Continue negotiation</Link><Link href={`/product/${item.productId === "p-1001" ? "industrial-solar-inverter" : item.productId === "p-1002" ? "hydraulic-excavator-320" : "water-filtration-unit-model-a"}`} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold">View product</Link><Link href="/suppliers" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold">View supplier</Link><Link href={`/order/create/${item.id}`} className="rounded-full border border-indigo-200 px-4 py-2 text-sm font-semibold text-indigo-700">Create order</Link></div></Card>)}</div></PlatformShell>;
}
